mysql:
  dns: root:123456@tcp(127.0.0.1:3306)/ltt?charset=utf8mb4&parseTime=True&loc=Local
mongo:
  dns: mongodb://admin:12345678@127.0.0.1:27017/travelservice

auth:
  jwt:
    secret: "ltt"
    expire: 7
    issuer: "ltt"

